package com.hzj.ribbon.consumer.ribbonconsumer.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;


/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Tue Apr 23 11:00:51 CST 2019.</p>
 *
 * @author huangzijian
 */

@Entity
@Table ( name ="USER" )
public class User implements Serializable {


	private static final long serialVersionUID =  9152499766471349365L;

	@Id
   	@Column(name = "USERID" )
	private String userid;

   	@Column(name = "NAME" )
	private String name;

   	@Column(name = "AGE" )
	private String age;

   	@Column(name = "PORT" )
	private String port;

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public String getPort() {
		return this.port;
	}

	public void setPort(String port) {
		this.port = port;
	}

}
